#!/bin/bash

userName=$USER # Shows Current USer
today=$(date +%Y-%m-%d/%l:%M:$S) # Display current date and time in a specific format
comp_hostname=$(hostname) # Capture the hostname of the machine
userUptime=$(uptime | awk '{print $1}') # Shows System uptime information
cpuInfo=$(lscpu | awk '/Model name: / {print $3, $4, $5, $6, $7, $8, $9}') # Capture CPU model information
cpuSpeed=$(cat /proc/cpuinfo | grep -i 'cpu mhz' | head -n 1 | awk '{print $4}') # Shows CPU speed information from /proc/cpuinfo
ramSize=$(free -h | grep -i "mem:" | awk '{print $2}') # Shows total RAM size
osSource=$(cat /etc/os-release | grep "PRETTY_NAME" | cut -d= -f2) # Display OS information (Pretty_name from /etc/os-release
#display model name of disk
disks1=$(lsblk -dno model | tr -d '[:space:]' | cut -dS -f1)
#display sizes of disks
disksize1=$(lsblk -dno size | tail -n 3 | awk '{print $1}' | sed -n 'lp')
#display model name of disk2
disks2=$(lsblk -dno model | tr -d '[:space:]' | cut -dS -f2)
#display sizes of disks2
disksize2=$(lsblk -dno size | tail -n 2 | awk '{print $1}' | sed -n '1p')
vidCardMake=$(lshw -class display | grep -i 'vendor:' | cut -d ':' -f2) # shows vendor information of the video card
vidCard=$(lshw -class display | grep -i 'product:' | cut -d ':' -f2) # shows product information of the video card
ipAddress=$(ip addr show | awk '/inet /{print $2}' | sed -n '2p') # Shows the IP address 
fqdn=$(hostname -f) # Capture fully qualified domain name
hostAddress=$(ip addr show | awk '/inet /{print $2}' | cut -d '/' -f1 | sed -n '2p') #shows host address (Second IP address)
gatewayIP=$(ip route | awk '/default /{print $3}') # Shows default gateway IP address
networkMake=$(lshw -class network | awk '/vendor: /' | head -n 1 | cut -d ':' f2) # Cpature network interface vendor information
networkCard=$(lshw -class network | awk '/product: /' | head -n 1 | cut -d ':' f2) # Capture network interface product information
dnsServer=$(nmcli | awk '/servers: /{print $2}' | sed -n '1p') # Displaying the DNS server IP address
usersLoggedIn=$(getent passwd | tail -n 2 | cut -d ':' -f1) # Shows the currently logged in users
processCount=$(ps -A | wc -l) #Count the total number of processes running
memoryAllocation=$(free -h) #Capture memory allocation details
ufwRules=$(sudo ufw status) #shows the status of Uncomplicated Firewall (UFW)
diskSpace=$(df -hP) #shows disk space usage information for all partitions
listenPort=$(ss -tnlp) #Listening network ports

cat <<EOF


System Report generated by $userName, $today

System Information
------------------
HOSTNAME: $comp_hostname
OS: "$osSource"
Uptime: $userUptime

Hardware Information
--------------------
CPU: $cpuInfo
Speed: $cpuSpeed MHz
RAM: $ramSize
Disks: $disks1 - $diskSize1, $disks2 - $diskSize2

Videocard: $vidCardMake $vidCard

Network Information
-------------------
FQDN: $fqdn
Host Address: $hostAddress
Gateway IP: $gatewayIP
DNS Server: $dnsServer
Interface Name: $interface
IP Address: $ipAddress

System Status
-------------
Users Logged IN: $usersLoggedIn
Disk Space: $diskspace
Process Count: $processCount
Memory Allocation: $memoryAllocation
Listening Network Ports: $listenPort
UFW Rules: $ufwRules


EOF

